apiVersion: v1
kind: Service
metadata:
  name: onyxai
  labels:
    app.kubernetes.io/name: onyxai
    app.kubernetes.io/part-of: onyxai
    dokploy-fleet/project: onyxai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: onyxai
    app.kubernetes.io/part-of: onyxai
  ports:
    - name: http
      port: 80
      targetPort: 3000
