apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onyxai-live-apex
  labels:
    dokploy-fleet/project: onyxai
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: onyxai-live-apex-tls
      hosts:
        - onyxai.lol
        - www.onyxai.lol
  rules:
    - host: onyxai.lol
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onyxai
                port:
                  number: 80
