apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-preview.yaml
images:
  - name: registry.144.91.77.245.sslip.io/dokploy-fleet-onyxai-onyxai
    newTag: fb9bff07b2ece6cc6ba8e122e1a7d6cc5c741c91
