apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-preview.yaml
  - ingress-www.yaml
images:
  - name: registry.144.91.77.245.sslip.io/dokploy-fleet-onyxai-onyxai
    newTag: a156a10c73d6df821d0ae1208a067010c0821eb3
